default-username: ubuntu
default-host: localhost
default-port: 22
default-identity-file: foobar
services:
  nova-compute:
    - username: foo
      host: example.com
      port: 22
      identity-file: /tmp/id_rsa
  nova-api:
    - username: foo
      host: example.com
      port: 22
      identity-file: /tmp/id_rsa
